drivers: staging: qcacld-3.0: Fix clang error
../drivers/staging/qcacld-3.0/core/mac/src/sys/legacy/src/utils/src/parser_api.c:5914:14: error: argument 'mdie' of type 'uint8_t[3]' (aka 'unsigned char[3]') with mismatched bound [-Werror,-Warray-parameter]
                   uint8_t mdie[SIR_MDIE_SIZE])
                           ^
../drivers/staging/qcacld-3.0/core/mac/src/include/parser_api.h:1028:14: note: previously declared as 'uint8_t[]' (aka 'unsigned char[]') here
                   uint8_t mdie[]);
                           ^
1 error generated.

Signed-off-by: Pranav Vashi <neobuddy89@gmail.com>
(cherry picked from commit 4b5809d514b2dda305b3872fc6f0f561b1b9e9cd)