msm: camera: icp: fix -Wunsequenced
Fixes:
drivers/media/platform/msm/camera_floral/cam_icp/icp_hw/icp_hw_mgr/cam_icp_hw_mgr.c:3481:17:
error: multiple unsequenced modifications to 'num_cmd_buf'
[-Werror,-Wunsequenced]
num_cmd_buf-- : 0;
           ^
drivers/media/platform/msm/camera_floral/cam_icp/icp_hw/icp_hw_mgr/cam_icp_hw_mgr.c:3505:17:
error: multiple unsequenced modifications to 'num_cmd_buf'
[-Werror,-Wunsequenced]
num_cmd_buf-- : 0;
           ^

Bug: 155426751
Signed-off-by: Nick Desaulniers <ndesaulniers@google.com>
Change-Id: I0bdcf704fdce60d103143843ed9890330650b84e
(cherry picked from commit 69c70340cacfba2103bcd61a9c8a058ccd88960d)