rmnet: perf: Fix strict-prototypes warning in function declaration
../techpack/data/drivers/rmnet/perf/rmnet_perf_opt.c:715:27: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
rmnet_perf_free_hash_table()
                          ^
                           void
1 error generated.
(cherry picked from commit b235e61afc1df0b2cb68dd987949be0a1755eecd)